#!/bin/bash
	if [ $# -eq 0 ]; then
		echo "This door is locked... And seems pretty solid. But maybe it is thisty?"
	elif [ $# -eq 1 ]; then
        input=$(cat $1)
        p=${input:0:1}
        input=${input:1}
        if [[ "$p" = "3" ]]; then
            echo "Oh I see, you want to give me something to drink! So nice of you!"
            input=$(printf "%X" $input)
            input=${input:1}
            if [ $(git cat-file -t $input 2> /dev/null) ]
            then
                echo "Oh, it seems like something happened"
                git stash
                git checkout $input
            fi
        else
            echo "I said something to drink, not to eat!"
        fi
	else
		echo "What are you trying to do exactly...? You seem confused..."
	fi
