#!/bin/bash
	if [ $# -eq 0 ]; then
		echo "Do you want to take a shower?"
	elif [ $# -eq 1 ]; then
		echo "Do you really want to put something in the shower? I'm warning you: you'll clean up everything!"
        input=$(cat $1)
        mol=${input:1}
        echo "3$mol" > wet_stuff
	else
		echo "What are you trying to do exactly...? You seem confused..."
	fi
