#!/bin/bash
	if [ $# -eq 0 ]; then
		echo "This is a regular trash can. Just don't put in it anything too corrosive."
        echo "For instance, no hydrochloric acid, perchloric acid, nitric acid or sulfuric adic."
	elif [ $# -eq 1 ]; then
        rm $1
	else
		echo "One thing at a time please."
	fi
